import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { readFile } from "node:fs/promises";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const pdfjsGlobalName = "global" + "This";
const pdfjsTopLevelAwaitSnippet = `__webpack_exports__ = ${pdfjsGlobalName}.pdfjsLib = await (${pdfjsGlobalName}.pdfjsLibPromise = __webpack_exports__);`;
const pdfjsTopLevelAwaitReplacement = "var __vaultCoachPdfJsLibPromise = Promise.resolve(__webpack_exports__);";
const pdfjsSourceMapComment = "\n//# sourceMappingURL=pdf.mjs.map";
const pdfjsDefaultPromiseExport = "\nexport { __vaultCoachPdfJsLibPromise as default };";
const pdfjsWorkerGlobalAssignmentSnippet = `var __webpack_exports__ = ${pdfjsGlobalName}.pdfjsWorker = {};`;
const pdfjsWorkerGlobalAssignmentReplacement = "var __webpack_exports__ = {};";

const patchPdfjsForObsidianPluginPlugin = {
	name: "patch-pdfjs-for-obsidian-plugin",
	setup(build) {
		build.onLoad({ filter: /[\\/]pdfjs-dist[\\/]build[\\/]pdf\.mjs$/ }, async (args) => {
			const source = await readFile(args.path, "utf8");
			if (!source.includes(pdfjsTopLevelAwaitSnippet)) {
				throw new Error("Unable to patch pdf.js top-level await.");
			}
			if (!source.includes(pdfjsSourceMapComment)) {
				throw new Error("Unable to patch pdf.js default promise export.");
			}

			return {
				contents: source
					.replace(pdfjsTopLevelAwaitSnippet, pdfjsTopLevelAwaitReplacement)
					.replace(pdfjsSourceMapComment, `${pdfjsDefaultPromiseExport}${pdfjsSourceMapComment}`),
				loader: "js",
			};
		});

		build.onLoad({ filter: /[\\/]pdfjs-dist[\\/]build[\\/]pdf\.worker\.mjs$/ }, async (args) => {
			const source = await readFile(args.path, "utf8");
			if (!source.includes(pdfjsWorkerGlobalAssignmentSnippet)) {
				throw new Error("Unable to patch pdf.js worker global assignment.");
			}

			return {
				contents: source.replace(pdfjsWorkerGlobalAssignmentSnippet, pdfjsWorkerGlobalAssignmentReplacement),
				loader: "js",
			};
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [
		patchPdfjsForObsidianPluginPlugin,
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
